[package]
name = "hsmusicifier"
version = "0.1.0"
authors = ["leo60228 <leo@60228.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
attohttpc = "0.16.1"
heck = "0.3.2"
once_cell = "1.5.2"
regex = "1.4.3"
scraper = "0.12.0"
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.61"
url = "2.2.0"
